/******* LOGIN ACTIONS *********/
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

/******** LOGOUT ACTIONS *******/
export const LOGOUT_PENDING = "LOGOUT_PENDING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

/******** CHANGE PASSWORD ACTIONS *********/
export const CHANGE_PWD_PENDING = "CHANGE_PWD_PENDING";
export const CHANGE_PWD_SUCCESS = "CHANGE_PWD_SUCCESS";
export const CHANGE_PWD_FAIL = "CHANGE_PWD_FAIL";
