/******* QUESTION ACTIONS *********/

// export const ADD_QUESTION = "ADD_QUESTION";
export const SET_QUESTIONS = "SET_QUESTIONS";
export const CHANGE_QUESTION_STATUS = "CHANGE_QUESTION_STATUS";
export const GET_QUESTION_PENDING = "GET_QUESTION_PENDING";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_QUESTION_FAIL = "GET_QUESTION_FAIL";
export const ADD_QUESTION_PENDING = "ADD_QUESTION_PENDING";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_FAIL = "ADD_QUESTION_FAIL";
