/******* TEST ACTIONS *********/
export const TEST_PENDING = "TEST_PENDING";
export const TEST_COMPLETED = "TEST_COMPLETED";
export const TEST_GET_FAIL = "TEST_GET_FAIL";
export const TEST_GET_SUCCESS = "TEST_GET_SUCCESS";
export const TEST_GET_PENDING = "TEST_GET_PENDING";
export const TEST_CREATE_SUCCESS = "TEST_CREATE_SUCCESS";
export const TEST_CREATE_PENDING = "TEST_CREATE_PENDING";
export const TEST_CREATE_FAIL = "TEST_CREATE_FAIL";
export const TEST_GET_ALL_SUCCESS = "TEST_GET_ALL_SUCCESS";
export const TEST_SCHEDULE_PENDING = "TEST_SCHEDULE_PENDING";
export const TEST_SCHEDULE_SUCCESS = "TEST_SCHEDULE_SUCCESS";
export const TEST_SCHEDULE_FAIL = "TEST_SCHEDULE_FAIL";
export const COMPILE_PENDING = "COMPILE_PENDING";
export const COMPILE_SUCCESS = "COMPILE_SUCCESS";
export const COMPILE_FAIL = "COMPILE_FAIL";
