/******* TEST ACTIONS *********/
export const TEST_PENDING = "TEST_PENDING";
export const TEST_COMPLETED = "TEST_COMPLETED";
export const TEST_GET_FAIL = "TEST_GET_FAIL";
export const TEST_GET_SUCCESS = "TEST_GET_SUCCESS";
export const TEST_GET_PENDING = "TEST_GET_PENDING";
export const TEST_CREATE_SUCCESS = "TEST_CREATE_SUCCESS";
