dist: trusty

language: python
python: '3.5'
sudo: enabled

addons:
  apt:
    sources:
      - mysql-14.14-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test_codexpose;'

script:
  - cd backend/codexpose/
  - pip install -r requirements.txt
  - pylint --rcfile=../../.pylintrc codexpose
  - pycodestyle codexpose/
  - pylint --rcfile=../../.pylintrc interview/
  - pycodestyle interview/
  - touch codexpose.log
  - python manage.py test
#  - nosetests -v --with-coverage --cover-tests --cover-package=interview interview/tests/test*.py

after_success:
  - coveralls

notifications:
  slack: codexpose:Lk1VuZodnuuDanuPfGBbI86y
