# Generated by Django 2.0 on 2017-12-26 13:02

from django.db import migrations, models
import django.db.models.deletion
import interview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(unique=True)),
                ('question_type', models.CharField(max_length=20)),
                ('problem_statement', models.FileField(upload_to=interview.models.question_data_path)),
                ('test_cases', models.FileField(upload_to=interview.models.question_data_path)),
                ('skeleton', models.FileField(upload_to=interview.models.question_data_path)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.Test')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test_id',
            field=models.ManyToManyField(to='interview.Test'),
        ),
    ]
