# Generated by Django 2.0 on 2017-12-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='test_id',
            new_name='test',
        ),
    ]
