# Generated by Django 2.0 on 2017-12-27 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20171226_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('interviewer', 'Interviewer'), ('candidate', 'Candidate')], default='interviewer', max_length=20),
        ),
        migrations.AddField(
            model_name='usertestmapping',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Test'),
        ),
        migrations.AddField(
            model_name='usertestmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.User'),
        ),
    ]
